//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9177
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ServiceCompoundSoap
{
    
    void GetCompDetailToPay(string councilid, string searchtype, string searchvalue, string refsource, string secretkey);
    
    void UpdatePaymentWS(string councilid, string type, string nokompaun, string paydatetime, string payamt, string rcptno, string chequeno, string cardno, string paymode, string kodhasil, string refsource, string secretkey);
    
    string InsertEnforceractivity(GPSInfo gpsInfo, UserCredentials userCredentials);
    
    string InsertCompoundDetails(CompoundInfo CompoundInfo, UserCredentials userCredentials);
    
    string IsCompoundexist(string nodaftar, string key);
    
    string GetServerDatetime(string key);
    
    string InsertEnquirylog(ENQUIRYLOGInfo enquiryloginfo, UserCredentials userCredentials);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetCompDetailToPay", Namespace="http://aim-force.com.my")]
public partial class GetCompDetailToPayRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public string councilid;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=1)]
    public string searchtype;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=2)]
    public string searchvalue;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=3)]
    public string refsource;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=4)]
    public string secretkey;
    
    public GetCompDetailToPayRequest()
    {
    }
    
    public GetCompDetailToPayRequest(string councilid, string searchtype, string searchvalue, string refsource, string secretkey)
    {
        this.councilid = councilid;
        this.searchtype = searchtype;
        this.searchvalue = searchvalue;
        this.refsource = refsource;
        this.secretkey = secretkey;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetCompDetailToPayResponse", Namespace="http://aim-force.com.my")]
public partial class GetCompDetailToPayResponse
{
    
    public GetCompDetailToPayResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="UpdatePaymentWS", Namespace="http://aim-force.com.my")]
public partial class UpdatePaymentWSRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public string councilid;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=1)]
    public string type;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=2)]
    public string nokompaun;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=3)]
    public string paydatetime;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=4)]
    public string payamt;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=5)]
    public string rcptno;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=6)]
    public string chequeno;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=7)]
    public string cardno;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=8)]
    public string paymode;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=9)]
    public string kodhasil;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=10)]
    public string refsource;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=11)]
    public string secretkey;
    
    public UpdatePaymentWSRequest()
    {
    }
    
    public UpdatePaymentWSRequest(string councilid, string type, string nokompaun, string paydatetime, string payamt, string rcptno, string chequeno, string cardno, string paymode, string kodhasil, string refsource, string secretkey)
    {
        this.councilid = councilid;
        this.type = type;
        this.nokompaun = nokompaun;
        this.paydatetime = paydatetime;
        this.payamt = payamt;
        this.rcptno = rcptno;
        this.chequeno = chequeno;
        this.cardno = cardno;
        this.paymode = paymode;
        this.kodhasil = kodhasil;
        this.refsource = refsource;
        this.secretkey = secretkey;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="UpdatePaymentWSResponse", Namespace="http://aim-force.com.my")]
public partial class UpdatePaymentWSResponse
{
    
    public UpdatePaymentWSResponse()
    {
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aim-force.com.my")]
public partial class GPSInfo
{
    
    private string noDolphinField;
    
    private string enforcerIDField;
    
    private string activityDateField;
    
    private string activityTimeField;
    
    private string latitudeField;
    
    private string longitudeField;
    
    private string batterylifeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string NoDolphin
    {
        get
        {
            return this.noDolphinField;
        }
        set
        {
            this.noDolphinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string EnforcerID
    {
        get
        {
            return this.enforcerIDField;
        }
        set
        {
            this.enforcerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string ActivityDate
    {
        get
        {
            return this.activityDateField;
        }
        set
        {
            this.activityDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string ActivityTime
    {
        get
        {
            return this.activityTimeField;
        }
        set
        {
            this.activityTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string Latitude
    {
        get
        {
            return this.latitudeField;
        }
        set
        {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Longitude
    {
        get
        {
            return this.longitudeField;
        }
        set
        {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Batterylife
    {
        get
        {
            return this.batterylifeField;
        }
        set
        {
            this.batterylifeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aim-force.com.my")]
public partial class ENQUIRYLOGInfo
{
    
    private string noDaftarField;
    
    private string logDateField;
    
    private string dHIDField;
    
    private string kodPguatkuasaField;
    
    private string kodZonField;
    
    private string kodKawField;
    
    private string kodJalanField;
    
    private string statusField;
    
    private string latitudeField;
    
    private string longitudeField;
    
    private string logTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string NoDaftar
    {
        get
        {
            return this.noDaftarField;
        }
        set
        {
            this.noDaftarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string LogDate
    {
        get
        {
            return this.logDateField;
        }
        set
        {
            this.logDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string DHID
    {
        get
        {
            return this.dHIDField;
        }
        set
        {
            this.dHIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string KodPguatkuasa
    {
        get
        {
            return this.kodPguatkuasaField;
        }
        set
        {
            this.kodPguatkuasaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string KodZon
    {
        get
        {
            return this.kodZonField;
        }
        set
        {
            this.kodZonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string KodKaw
    {
        get
        {
            return this.kodKawField;
        }
        set
        {
            this.kodKawField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string KodJalan
    {
        get
        {
            return this.kodJalanField;
        }
        set
        {
            this.kodJalanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string Latitude
    {
        get
        {
            return this.latitudeField;
        }
        set
        {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Longitude
    {
        get
        {
            return this.longitudeField;
        }
        set
        {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string LogTime
    {
        get
        {
            return this.logTimeField;
        }
        set
        {
            this.logTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aim-force.com.my")]
public partial class CompoundInfo
{
    
    private string compoundNumberField;
    
    private string compoundTypeField;
    
    private string actcodeField;
    
    private string offenseField;
    
    private string offense2Field;
    
    private string areaField;
    
    private string streetField;
    
    private string streetDescrField;
    
    private string compDateField;
    
    private string compTimeField;
    
    private string enforcerField;
    
    private string witnessField;
    
    private string cetakcountField;
    
    private string vehicleNoField;
    
    private string jenkenField;
    
    private string kodkenField;
    
    private string vehicleDescrField;
    
    private string colorField;
    
    private string colorDescrField;
    
    private string pdDateField;
    
    private string pdTimeField;
    
    private string roadtaxNoField;
    
    private string parkingLotField;
    
    private string amnkmpField;
    
    private string compDescrField;
    
    private string pdNoField;
    
    private string catatanField;
    
    private string ruanganNoField;
    
    private string noRujukanField;
    
    private string noSyarikatField;
    
    private string namaSyarikatField;
    
    private string noicField;
    
    private string namaField;
    
    private string lokasiField;
    
    private string alamat2Field;
    
    private string alamat3Field;
    
    private string offenderTypeField;
    
    private string kodHasilField;
    
    private string noDaftarField;
    
    private string isSucessField;
    
    private string tarafKompaunField;
    
    private string petakField;
    
    private string seksyenField;
    
    private string kodaktaField;
    
    private string kodSalahField;
    
    private string kodJalanField;
    
    private string kodPguatkuasaField;
    
    private string kodWarnaField;
    
    private string kodKenField;
    
    private string kodkawField;
    
    private string mukimField;
    
    private string zoneField;
    
    private string pubWitnessField;
    
    private string printCntField;
    
    private string tempatjadiField;
    
    private string issueDateField;
    
    private string issueTimeField;
    
    private string kadarField;
    
    private string namaPenerimaField;
    
    private string icPenerimaField;
    
    private string carTypeField;
    
    private string carColorField;
    
    private string carTypeDescField;
    
    private string carColorDescField;
    
    private string roadTaxField;
    
    private string amnkmp2Field;
    
    private string amnkmp3Field;
    
    private string amnkmp4Field;
    
    private string deliveryCodeField;
    
    private string companyField;
    
    private string companyNameField;
    
    private string offenderIcField;
    
    private string offenderNameField;
    
    private string alamat1Field;
    
    private string unitNoField;
    
    private string buildingField;
    
    private string jalanField;
    
    private string tamanField;
    
    private string postCodeField;
    
    private string cityField;
    
    private string stateField;
    
    private string noTaksiranField;
    
    private string blackListCountField;
    
    private string latitudeField;
    
    private string longitudeField;
    
    private string tujuanField;
    
    private string perniagaanField;
    
    private string tempohdateField;
    
    private string muatanField;
    
    private string scandatetimeField;
    
    private string nokunciField;
    
    private string waktukunciField;
    
    private string amnbukaField;
    
    private string amntowField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string CompoundNumber
    {
        get
        {
            return this.compoundNumberField;
        }
        set
        {
            this.compoundNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string CompoundType
    {
        get
        {
            return this.compoundTypeField;
        }
        set
        {
            this.compoundTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Actcode
    {
        get
        {
            return this.actcodeField;
        }
        set
        {
            this.actcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string offense
    {
        get
        {
            return this.offenseField;
        }
        set
        {
            this.offenseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string offense2
    {
        get
        {
            return this.offense2Field;
        }
        set
        {
            this.offense2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string area
    {
        get
        {
            return this.areaField;
        }
        set
        {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string street
    {
        get
        {
            return this.streetField;
        }
        set
        {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string streetDescr
    {
        get
        {
            return this.streetDescrField;
        }
        set
        {
            this.streetDescrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string compDate
    {
        get
        {
            return this.compDateField;
        }
        set
        {
            this.compDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string compTime
    {
        get
        {
            return this.compTimeField;
        }
        set
        {
            this.compTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string enforcer
    {
        get
        {
            return this.enforcerField;
        }
        set
        {
            this.enforcerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public string witness
    {
        get
        {
            return this.witnessField;
        }
        set
        {
            this.witnessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public string cetakcount
    {
        get
        {
            return this.cetakcountField;
        }
        set
        {
            this.cetakcountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public string vehicleNo
    {
        get
        {
            return this.vehicleNoField;
        }
        set
        {
            this.vehicleNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public string jenken
    {
        get
        {
            return this.jenkenField;
        }
        set
        {
            this.jenkenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=15)]
    public string kodken
    {
        get
        {
            return this.kodkenField;
        }
        set
        {
            this.kodkenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=16)]
    public string vehicleDescr
    {
        get
        {
            return this.vehicleDescrField;
        }
        set
        {
            this.vehicleDescrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=17)]
    public string color
    {
        get
        {
            return this.colorField;
        }
        set
        {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=18)]
    public string colorDescr
    {
        get
        {
            return this.colorDescrField;
        }
        set
        {
            this.colorDescrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=19)]
    public string PdDate
    {
        get
        {
            return this.pdDateField;
        }
        set
        {
            this.pdDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=20)]
    public string pdTime
    {
        get
        {
            return this.pdTimeField;
        }
        set
        {
            this.pdTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=21)]
    public string roadtaxNo
    {
        get
        {
            return this.roadtaxNoField;
        }
        set
        {
            this.roadtaxNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=22)]
    public string parkingLot
    {
        get
        {
            return this.parkingLotField;
        }
        set
        {
            this.parkingLotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=23)]
    public string amnkmp
    {
        get
        {
            return this.amnkmpField;
        }
        set
        {
            this.amnkmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=24)]
    public string compDescr
    {
        get
        {
            return this.compDescrField;
        }
        set
        {
            this.compDescrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=25)]
    public string pdNo
    {
        get
        {
            return this.pdNoField;
        }
        set
        {
            this.pdNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=26)]
    public string catatan
    {
        get
        {
            return this.catatanField;
        }
        set
        {
            this.catatanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=27)]
    public string ruanganNo
    {
        get
        {
            return this.ruanganNoField;
        }
        set
        {
            this.ruanganNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=28)]
    public string noRujukan
    {
        get
        {
            return this.noRujukanField;
        }
        set
        {
            this.noRujukanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=29)]
    public string noSyarikat
    {
        get
        {
            return this.noSyarikatField;
        }
        set
        {
            this.noSyarikatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=30)]
    public string namaSyarikat
    {
        get
        {
            return this.namaSyarikatField;
        }
        set
        {
            this.namaSyarikatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=31)]
    public string noic
    {
        get
        {
            return this.noicField;
        }
        set
        {
            this.noicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=32)]
    public string nama
    {
        get
        {
            return this.namaField;
        }
        set
        {
            this.namaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=33)]
    public string lokasi
    {
        get
        {
            return this.lokasiField;
        }
        set
        {
            this.lokasiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=34)]
    public string alamat2
    {
        get
        {
            return this.alamat2Field;
        }
        set
        {
            this.alamat2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=35)]
    public string alamat3
    {
        get
        {
            return this.alamat3Field;
        }
        set
        {
            this.alamat3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=36)]
    public string offenderType
    {
        get
        {
            return this.offenderTypeField;
        }
        set
        {
            this.offenderTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=37)]
    public string kodHasil
    {
        get
        {
            return this.kodHasilField;
        }
        set
        {
            this.kodHasilField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=38)]
    public string noDaftar
    {
        get
        {
            return this.noDaftarField;
        }
        set
        {
            this.noDaftarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=39)]
    public string isSucess
    {
        get
        {
            return this.isSucessField;
        }
        set
        {
            this.isSucessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=40)]
    public string tarafKompaun
    {
        get
        {
            return this.tarafKompaunField;
        }
        set
        {
            this.tarafKompaunField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=41)]
    public string petak
    {
        get
        {
            return this.petakField;
        }
        set
        {
            this.petakField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=42)]
    public string seksyen
    {
        get
        {
            return this.seksyenField;
        }
        set
        {
            this.seksyenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=43)]
    public string Kodakta
    {
        get
        {
            return this.kodaktaField;
        }
        set
        {
            this.kodaktaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=44)]
    public string kodSalah
    {
        get
        {
            return this.kodSalahField;
        }
        set
        {
            this.kodSalahField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=45)]
    public string kodJalan
    {
        get
        {
            return this.kodJalanField;
        }
        set
        {
            this.kodJalanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=46)]
    public string KodPguatkuasa
    {
        get
        {
            return this.kodPguatkuasaField;
        }
        set
        {
            this.kodPguatkuasaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=47)]
    public string KodWarna
    {
        get
        {
            return this.kodWarnaField;
        }
        set
        {
            this.kodWarnaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=48)]
    public string KodKen
    {
        get
        {
            return this.kodKenField;
        }
        set
        {
            this.kodKenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=49)]
    public string kodkaw
    {
        get
        {
            return this.kodkawField;
        }
        set
        {
            this.kodkawField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=50)]
    public string Mukim
    {
        get
        {
            return this.mukimField;
        }
        set
        {
            this.mukimField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=51)]
    public string Zone
    {
        get
        {
            return this.zoneField;
        }
        set
        {
            this.zoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=52)]
    public string PubWitness
    {
        get
        {
            return this.pubWitnessField;
        }
        set
        {
            this.pubWitnessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=53)]
    public string PrintCnt
    {
        get
        {
            return this.printCntField;
        }
        set
        {
            this.printCntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=54)]
    public string Tempatjadi
    {
        get
        {
            return this.tempatjadiField;
        }
        set
        {
            this.tempatjadiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=55)]
    public string IssueDate
    {
        get
        {
            return this.issueDateField;
        }
        set
        {
            this.issueDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=56)]
    public string IssueTime
    {
        get
        {
            return this.issueTimeField;
        }
        set
        {
            this.issueTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=57)]
    public string Kadar
    {
        get
        {
            return this.kadarField;
        }
        set
        {
            this.kadarField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=58)]
    public string NamaPenerima
    {
        get
        {
            return this.namaPenerimaField;
        }
        set
        {
            this.namaPenerimaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=59)]
    public string IcPenerima
    {
        get
        {
            return this.icPenerimaField;
        }
        set
        {
            this.icPenerimaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=60)]
    public string CarType
    {
        get
        {
            return this.carTypeField;
        }
        set
        {
            this.carTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=61)]
    public string CarColor
    {
        get
        {
            return this.carColorField;
        }
        set
        {
            this.carColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=62)]
    public string CarTypeDesc
    {
        get
        {
            return this.carTypeDescField;
        }
        set
        {
            this.carTypeDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=63)]
    public string CarColorDesc
    {
        get
        {
            return this.carColorDescField;
        }
        set
        {
            this.carColorDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=64)]
    public string RoadTax
    {
        get
        {
            return this.roadTaxField;
        }
        set
        {
            this.roadTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=65)]
    public string amnkmp2
    {
        get
        {
            return this.amnkmp2Field;
        }
        set
        {
            this.amnkmp2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=66)]
    public string amnkmp3
    {
        get
        {
            return this.amnkmp3Field;
        }
        set
        {
            this.amnkmp3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=67)]
    public string amnkmp4
    {
        get
        {
            return this.amnkmp4Field;
        }
        set
        {
            this.amnkmp4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=68)]
    public string DeliveryCode
    {
        get
        {
            return this.deliveryCodeField;
        }
        set
        {
            this.deliveryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=69)]
    public string Company
    {
        get
        {
            return this.companyField;
        }
        set
        {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=70)]
    public string CompanyName
    {
        get
        {
            return this.companyNameField;
        }
        set
        {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=71)]
    public string OffenderIc
    {
        get
        {
            return this.offenderIcField;
        }
        set
        {
            this.offenderIcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=72)]
    public string OffenderName
    {
        get
        {
            return this.offenderNameField;
        }
        set
        {
            this.offenderNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=73)]
    public string Alamat1
    {
        get
        {
            return this.alamat1Field;
        }
        set
        {
            this.alamat1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=74)]
    public string UnitNo
    {
        get
        {
            return this.unitNoField;
        }
        set
        {
            this.unitNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=75)]
    public string Building
    {
        get
        {
            return this.buildingField;
        }
        set
        {
            this.buildingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=76)]
    public string Jalan
    {
        get
        {
            return this.jalanField;
        }
        set
        {
            this.jalanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=77)]
    public string Taman
    {
        get
        {
            return this.tamanField;
        }
        set
        {
            this.tamanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=78)]
    public string PostCode
    {
        get
        {
            return this.postCodeField;
        }
        set
        {
            this.postCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=79)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=80)]
    public string State
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=81)]
    public string NoTaksiran
    {
        get
        {
            return this.noTaksiranField;
        }
        set
        {
            this.noTaksiranField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=82)]
    public string BlackListCount
    {
        get
        {
            return this.blackListCountField;
        }
        set
        {
            this.blackListCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=83)]
    public string Latitude
    {
        get
        {
            return this.latitudeField;
        }
        set
        {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=84)]
    public string Longitude
    {
        get
        {
            return this.longitudeField;
        }
        set
        {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=85)]
    public string tujuan
    {
        get
        {
            return this.tujuanField;
        }
        set
        {
            this.tujuanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=86)]
    public string perniagaan
    {
        get
        {
            return this.perniagaanField;
        }
        set
        {
            this.perniagaanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=87)]
    public string tempohdate
    {
        get
        {
            return this.tempohdateField;
        }
        set
        {
            this.tempohdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=88)]
    public string muatan
    {
        get
        {
            return this.muatanField;
        }
        set
        {
            this.muatanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=89)]
    public string scandatetime
    {
        get
        {
            return this.scandatetimeField;
        }
        set
        {
            this.scandatetimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=90)]
    public string nokunci
    {
        get
        {
            return this.nokunciField;
        }
        set
        {
            this.nokunciField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=91)]
    public string waktukunci
    {
        get
        {
            return this.waktukunciField;
        }
        set
        {
            this.waktukunciField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=92)]
    public string amnbuka
    {
        get
        {
            return this.amnbukaField;
        }
        set
        {
            this.amnbukaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=93)]
    public string amntow
    {
        get
        {
            return this.amntowField;
        }
        set
        {
            this.amntowField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aim-force.com.my")]
public partial class UserCredentials
{
    
    private string useridField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string userid
    {
        get
        {
            return this.useridField;
        }
        set
        {
            this.useridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="InsertEnforceractivity", Namespace="http://aim-force.com.my")]
public partial class InsertEnforceractivityRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public GPSInfo gpsInfo;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=1)]
    public UserCredentials userCredentials;
    
    public InsertEnforceractivityRequest()
    {
    }
    
    public InsertEnforceractivityRequest(GPSInfo gpsInfo, UserCredentials userCredentials)
    {
        this.gpsInfo = gpsInfo;
        this.userCredentials = userCredentials;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="InsertEnforceractivityResponse", Namespace="http://aim-force.com.my")]
public partial class InsertEnforceractivityResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public string InsertEnforceractivityResult;
    
    public InsertEnforceractivityResponse()
    {
    }
    
    public InsertEnforceractivityResponse(string InsertEnforceractivityResult)
    {
        this.InsertEnforceractivityResult = InsertEnforceractivityResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="InsertCompoundDetails", Namespace="http://aim-force.com.my")]
public partial class InsertCompoundDetailsRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public CompoundInfo CompoundInfo;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=1)]
    public UserCredentials userCredentials;
    
    public InsertCompoundDetailsRequest()
    {
    }
    
    public InsertCompoundDetailsRequest(CompoundInfo CompoundInfo, UserCredentials userCredentials)
    {
        this.CompoundInfo = CompoundInfo;
        this.userCredentials = userCredentials;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="InsertCompoundDetailsResponse", Namespace="http://aim-force.com.my")]
public partial class InsertCompoundDetailsResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public string InsertCompoundDetailsResult;
    
    public InsertCompoundDetailsResponse()
    {
    }
    
    public InsertCompoundDetailsResponse(string InsertCompoundDetailsResult)
    {
        this.InsertCompoundDetailsResult = InsertCompoundDetailsResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="IsCompoundexist", Namespace="http://aim-force.com.my")]
public partial class IsCompoundexistRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public string nodaftar;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=1)]
    public string key;
    
    public IsCompoundexistRequest()
    {
    }
    
    public IsCompoundexistRequest(string nodaftar, string key)
    {
        this.nodaftar = nodaftar;
        this.key = key;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="IsCompoundexistResponse", Namespace="http://aim-force.com.my")]
public partial class IsCompoundexistResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public string IsCompoundexistResult;
    
    public IsCompoundexistResponse()
    {
    }
    
    public IsCompoundexistResponse(string IsCompoundexistResult)
    {
        this.IsCompoundexistResult = IsCompoundexistResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetServerDatetime", Namespace="http://aim-force.com.my")]
public partial class GetServerDatetimeRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public string key;
    
    public GetServerDatetimeRequest()
    {
    }
    
    public GetServerDatetimeRequest(string key)
    {
        this.key = key;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetServerDatetimeResponse", Namespace="http://aim-force.com.my")]
public partial class GetServerDatetimeResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public string GetServerDatetimeResult;
    
    public GetServerDatetimeResponse()
    {
    }
    
    public GetServerDatetimeResponse(string GetServerDatetimeResult)
    {
        this.GetServerDatetimeResult = GetServerDatetimeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="InsertEnquirylog", Namespace="http://aim-force.com.my")]
public partial class InsertEnquirylogRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public ENQUIRYLOGInfo enquiryloginfo;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=1)]
    public UserCredentials userCredentials;
    
    public InsertEnquirylogRequest()
    {
    }
    
    public InsertEnquirylogRequest(ENQUIRYLOGInfo enquiryloginfo, UserCredentials userCredentials)
    {
        this.enquiryloginfo = enquiryloginfo;
        this.userCredentials = userCredentials;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="InsertEnquirylogResponse", Namespace="http://aim-force.com.my")]
public partial class InsertEnquirylogResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://aim-force.com.my", Order=0)]
    public string InsertEnquirylogResult;
    
    public InsertEnquirylogResponse()
    {
    }
    
    public InsertEnquirylogResponse(string InsertEnquirylogResult)
    {
        this.InsertEnquirylogResult = InsertEnquirylogResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServiceCompoundSoapClient : Microsoft.Tools.ServiceModel.CFClientBase<ServiceCompoundSoap>, ServiceCompoundSoap
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://localhost:65206/servicecompound.asmx");
    
    public ServiceCompoundSoapClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public ServiceCompoundSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private GetCompDetailToPayResponse GetCompDetailToPay(GetCompDetailToPayRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://aim-force.com.my/GetCompDetailToPay";
        info.RequestIsWrapped = true;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = true;
        GetCompDetailToPayResponse retVal = base.Invoke<GetCompDetailToPayRequest, GetCompDetailToPayResponse>(info, request);
        return retVal;
    }
    
    public void GetCompDetailToPay(string councilid, string searchtype, string searchvalue, string refsource, string secretkey)
    {
        GetCompDetailToPayRequest request = new GetCompDetailToPayRequest(councilid, searchtype, searchvalue, refsource, secretkey);
        GetCompDetailToPayResponse response = this.GetCompDetailToPay(request);
    }
    
    private UpdatePaymentWSResponse UpdatePaymentWS(UpdatePaymentWSRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://aim-force.com.my/UpdatePaymentWS";
        info.RequestIsWrapped = true;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = true;
        UpdatePaymentWSResponse retVal = base.Invoke<UpdatePaymentWSRequest, UpdatePaymentWSResponse>(info, request);
        return retVal;
    }
    
    public void UpdatePaymentWS(string councilid, string type, string nokompaun, string paydatetime, string payamt, string rcptno, string chequeno, string cardno, string paymode, string kodhasil, string refsource, string secretkey)
    {
        UpdatePaymentWSRequest request = new UpdatePaymentWSRequest(councilid, type, nokompaun, paydatetime, payamt, rcptno, chequeno, cardno, paymode, kodhasil, refsource, secretkey);
        UpdatePaymentWSResponse response = this.UpdatePaymentWS(request);
    }
    
    private InsertEnforceractivityResponse InsertEnforceractivity(InsertEnforceractivityRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://aim-force.com.my/InsertEnforceractivity";
        info.RequestIsWrapped = true;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = true;
        InsertEnforceractivityResponse retVal = base.Invoke<InsertEnforceractivityRequest, InsertEnforceractivityResponse>(info, request);
        return retVal;
    }
    
    public string InsertEnforceractivity(GPSInfo gpsInfo, UserCredentials userCredentials)
    {
        InsertEnforceractivityRequest request = new InsertEnforceractivityRequest(gpsInfo, userCredentials);
        InsertEnforceractivityResponse response = this.InsertEnforceractivity(request);
        return response.InsertEnforceractivityResult;
    }
    
    private InsertCompoundDetailsResponse InsertCompoundDetails(InsertCompoundDetailsRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://aim-force.com.my/InsertCompoundDetails";
        info.RequestIsWrapped = true;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = true;
        InsertCompoundDetailsResponse retVal = base.Invoke<InsertCompoundDetailsRequest, InsertCompoundDetailsResponse>(info, request);
        return retVal;
    }
    
    public string InsertCompoundDetails(CompoundInfo CompoundInfo, UserCredentials userCredentials)
    {
        InsertCompoundDetailsRequest request = new InsertCompoundDetailsRequest(CompoundInfo, userCredentials);
        InsertCompoundDetailsResponse response = this.InsertCompoundDetails(request);
        return response.InsertCompoundDetailsResult;
    }
    
    private IsCompoundexistResponse IsCompoundexist(IsCompoundexistRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://aim-force.com.my/IsCompoundexist";
        info.RequestIsWrapped = true;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = true;
        IsCompoundexistResponse retVal = base.Invoke<IsCompoundexistRequest, IsCompoundexistResponse>(info, request);
        return retVal;
    }
    
    public string IsCompoundexist(string nodaftar, string key)
    {
        IsCompoundexistRequest request = new IsCompoundexistRequest(nodaftar, key);
        IsCompoundexistResponse response = this.IsCompoundexist(request);
        return response.IsCompoundexistResult;
    }
    
    private GetServerDatetimeResponse GetServerDatetime(GetServerDatetimeRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://aim-force.com.my/GetServerDatetime";
        info.RequestIsWrapped = true;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = true;
        GetServerDatetimeResponse retVal = base.Invoke<GetServerDatetimeRequest, GetServerDatetimeResponse>(info, request);
        return retVal;
    }
    
    public string GetServerDatetime(string key)
    {
        GetServerDatetimeRequest request = new GetServerDatetimeRequest(key);
        GetServerDatetimeResponse response = this.GetServerDatetime(request);
        return response.GetServerDatetimeResult;
    }
    
    private InsertEnquirylogResponse InsertEnquirylog(InsertEnquirylogRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://aim-force.com.my/InsertEnquirylog";
        info.RequestIsWrapped = true;
        info.ReplyAction = "*";
        info.ResponseIsWrapped = true;
        InsertEnquirylogResponse retVal = base.Invoke<InsertEnquirylogRequest, InsertEnquirylogResponse>(info, request);
        return retVal;
    }
    
    public string InsertEnquirylog(ENQUIRYLOGInfo enquiryloginfo, UserCredentials userCredentials)
    {
        InsertEnquirylogRequest request = new InsertEnquirylogRequest(enquiryloginfo, userCredentials);
        InsertEnquirylogResponse response = this.InsertEnquirylog(request);
        return response.InsertEnquirylogResult;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        //if ((IsSecureMessageBinding(binding) == false))
        //{
        //    return;
        //}
        //System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        //ApplyProtection("http://aim-force.com.my/GetCompDetailToPay", cpr.IncomingSignatureParts, true);
        //ApplyProtection("http://aim-force.com.my/GetCompDetailToPay", cpr.IncomingEncryptionParts, true);
        //ApplyProtection("http://aim-force.com.my/UpdatePaymentWS", cpr.IncomingSignatureParts, true);
        //ApplyProtection("http://aim-force.com.my/UpdatePaymentWS", cpr.IncomingEncryptionParts, true);
        //ApplyProtection("http://aim-force.com.my/InsertEnforceractivity", cpr.IncomingSignatureParts, true);
        //ApplyProtection("http://aim-force.com.my/InsertEnforceractivity", cpr.IncomingEncryptionParts, true);
        //ApplyProtection("http://aim-force.com.my/InsertCompoundDetails", cpr.IncomingSignatureParts, true);
        //ApplyProtection("http://aim-force.com.my/InsertCompoundDetails", cpr.IncomingEncryptionParts, true);
        //ApplyProtection("http://aim-force.com.my/IsCompoundexist", cpr.IncomingSignatureParts, true);
        //ApplyProtection("http://aim-force.com.my/IsCompoundexist", cpr.IncomingEncryptionParts, true);
        //ApplyProtection("http://aim-force.com.my/GetServerDatetime", cpr.IncomingSignatureParts, true);
        //ApplyProtection("http://aim-force.com.my/GetServerDatetime", cpr.IncomingEncryptionParts, true);
        //ApplyProtection("http://aim-force.com.my/InsertEnquirylog", cpr.IncomingSignatureParts, true);
        //ApplyProtection("http://aim-force.com.my/InsertEnquirylog", cpr.IncomingEncryptionParts, true);
        //if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        //{
        //    ApplyProtection("*", cpr.OutgoingSignatureParts, true);
        //    ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        //}
        //else
        //{
        //    ApplyProtection("*", cpr.OutgoingSignatureParts, true);
        //    ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        //}
        //this.Parameters.Add(cpr);
    }
}
